# Generated by Django 4.0.6 on 2022-07-26 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CampaignName', models.CharField(blank=True, max_length=255, null=True)),
                ('CampaignStatus', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=10, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=10, null=True)),
                ('otp', models.CharField(default=359, max_length=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServiceName', models.CharField(blank=True, max_length=255, null=True)),
                ('campaign_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.campaign')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='user_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user1'),
        ),
    ]
