# Generated by Django 4.0.6 on 2022-07-27 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user1',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='user1',
            name='username',
        ),
    ]
