# Generated by Django 4.0.6 on 2022-08-03 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_data_summary_upload_req_data_summary_upload_res_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_summary',
            name='recordID',
        ),
        migrations.DeleteModel(
            name='Campaign',
        ),
        migrations.DeleteModel(
            name='Data_Summary',
        ),
        migrations.DeleteModel(
            name='User1',
        ),
    ]
