# Generated by Django 4.0.6 on 2022-08-03 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0007_remove_data_summary_recordid_delete_campaign_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CampaignName', models.CharField(blank=True, max_length=255, null=True)),
                ('CampaignStatus', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(blank=True, max_length=10, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Data_Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, max_length=10)),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('speechFile', models.CharField(blank=True, max_length=50, null=True)),
                ('API_Type', models.CharField(blank=True, max_length=50, null=True)),
                ('upload_req', models.CharField(blank=True, max_length=255, null=True)),
                ('upload_res', models.CharField(blank=True, max_length=255, null=True)),
                ('voiceshoot_req', models.CharField(blank=True, max_length=255, null=True)),
                ('voiceshoot_res', models.CharField(blank=True, max_length=255, null=True)),
                ('recordID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.campaign')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='user_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user1'),
        ),
    ]
