# Generated by Django 4.0.6 on 2022-08-03 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_summary',
            name='upload_req',
        ),
        migrations.RemoveField(
            model_name='data_summary',
            name='upload_res',
        ),
        migrations.RemoveField(
            model_name='data_summary',
            name='voiceshoot_req',
        ),
        migrations.RemoveField(
            model_name='data_summary',
            name='voiceshoot_res',
        ),
    ]
