# Generated by Django 4.0.6 on 2022-08-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_data_summary_upload_req_data_summary_upload_res_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_summary',
            old_name='API_Type',
            new_name='TTS_Provider',
        ),
        migrations.AddField(
            model_name='data_summary',
            name='Voice_API',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
