# Generated by Django 4.0.6 on 2022-08-05 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_rename_api_type_data_summary_tts_provider_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data_Summary',
        ),
    ]
