# Generated by Django 4.0.6 on 2022-08-05 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_delete_data_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, max_length=10)),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('speechFile', models.CharField(blank=True, max_length=50, null=True)),
                ('TTS_Provider', models.CharField(blank=True, max_length=50, null=True)),
                ('Voice_API', models.CharField(blank=True, max_length=50, null=True)),
                ('upload_req', models.CharField(blank=True, max_length=255, null=True)),
                ('upload_res', models.JSONField(blank=True, max_length=255, null=True)),
                ('voiceshoot_req', models.CharField(blank=True, max_length=255, null=True)),
                ('voiceshoot_res', models.JSONField(blank=True, max_length=255, null=True)),
                ('recordID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.campaign')),
            ],
        ),
    ]
