# Generated by Django 4.0.6 on 2022-08-05 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_data_summary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data_Summary',
        ),
    ]
