# Generated by Django 4.0.6 on 2022-08-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_data_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='user1',
            name='voice_API',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
