# Generated by Django 4.0.6 on 2022-08-05 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_data_summary_status_voice_api'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user1',
            name='voice_API',
        ),
    ]
