# Generated by Django 4.0.6 on 2022-08-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_remove_user1_voice_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_summary',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
