# Generated by Django 4.0.6 on 2022-08-10 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_remove_data_summary_recordid_remove_voice_api_u_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CampaignName', models.CharField(blank=True, max_length=255, null=True)),
                ('CampaignStatus', models.CharField(blank=True, max_length=255, null=True)),
                ('user_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user1')),
            ],
        ),
        migrations.CreateModel(
            name='Voice_API',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_API', models.CharField(blank=True, max_length=255, null=True)),
                ('upload_url', models.CharField(blank=True, max_length=255, null=True)),
                ('voiceshoot_url', models.CharField(blank=True, max_length=255, null=True)),
                ('u_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user1')),
            ],
        ),
        migrations.CreateModel(
            name='Data_Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, max_length=10)),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('speechFile', models.CharField(blank=True, max_length=50, null=True)),
                ('TTS_Provider', models.CharField(blank=True, max_length=50, null=True)),
                ('Voice_API', models.CharField(blank=True, max_length=50, null=True)),
                ('upload_req', models.CharField(blank=True, max_length=255, null=True)),
                ('upload_res', models.JSONField(blank=True, max_length=255, null=True)),
                ('voiceshoot_req', models.CharField(blank=True, max_length=255, null=True)),
                ('voiceshoot_res', models.JSONField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='Pending', max_length=10)),
                ('recordID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.campaign')),
            ],
        ),
    ]
