# Generated by Django 4.0.6 on 2022-08-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_campaign_record_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice_api',
            name='caller_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='voice_api',
            name='domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='voice_api',
            name='plan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='voice_api',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='voice_api',
            name='u_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
